### ISSUE TITLE
Loop infinity

### ISSUE THREAD

**Issue by Colerar** [InsanusMokrassar/krontab#65] opened 2023-06-28 19:10 UTC
<img width="1590" alt="image" src="https://github.com/InsanusMokrassar/krontab/assets/62297254/90b54a4d-1f8e-4224-989e-49caedf79220">

<img width="738" alt="image" src="https://github.com/InsanusMokrassar/krontab/assets/62297254/94e9cb8a-3ea1-42b1-b392-043c3b81e90b">

At 2023-06-28 19:58 UTC, it can be easily reproduced with following code:

```kotlin
suspend fun main() {
  doInfinity("0 0 8 /3 *") {
    println("Hello")
  }
}
```

**Comment by InsanusMokrassar** [comment] 2023-07-02 10:38
Hi again. @Colerar I have tested your case and found next points:

* Default context of `runBlocking` (as well as in `suspend main`) do not handle delays correctly. I have created next test and it was working just as you described:
```kotlin
@Test
fun simple() {
    runTest {
        doInfinity("0 0 8 /3 *") {
            delay(1)
            println(it)
        }
    }
}
```
* But them I have added normal coroutine scope and you sample was working correctly:
```kotlin
@Test
fun simple() {
    runTest {
        CoroutineScope(Dispatchers.Default).launch {
            doInfinity("0 0 8 /3 *") {
                delay(1)
                println(it)
            }
        }.join()
    }
}
```

So, it looks like the coroutine scope of `runBlocking` (and `suspend main`) is not suitable at least for correct handling of `delay`s


Anyway, I would like to know, how will work the next code for you:

```kotlin
suspend main() {
    CoroutineScope(Dispatchers.Default).launch {
        doInfinity("0 0 8 /3 *") {
            delay(1)
            println(it)
        }
    }.join()
}
```

Please, close this issue or at least comment with the results of your try :) (anyway thank you for that issue, I get know something new)

**Comment by InsanusMokrassar** [comment] 2023-07-05 14:03
Hello :) I have checked one more time the next sample (ready for copy-paste in clear gradle project with kotlin `1.8.21` and krontab `2.1.1`:

```kotlin
import dev.inmo.krontab.doInfinity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

suspend fun main() {
    CoroutineScope(Dispatchers.Default).launch {
        doInfinity("0 0 8 /3 *") {
            println(it)
        }
    }.join()
}
```

So, this sample used approximately 0% and 15-20 mb (I think, it can be related to profiler attachment). Anyway, could you please write your version of kotlin, library, java and some other environment. It may help me to catch the error

**Comment by InsanusMokrassar** [comment] 2023-07-17 06:44
Hello and thank you :) what about java and OS on your device?

**Comment by InsanusMokrassar** [comment] 2023-07-17 10:06
Ok, could you please share your sample project with this issue?

**Comment by InsanusMokrassar** [comment] 2023-07-17 12:22
Runned with `./gradlew run`:

```bash
> Task :app:run
OS: Linux-amd64-6.3.9-060309-generic
JVM: 1.8-Temurin
Current system time: 2023-07-17T12:17:35.074Z
Running krontab...
[0] Free mem = 231833200
[1] Free mem = 225431528
[2] Free mem = 225431528
[3] Free mem = 225431528
[4] Free mem = 225431528
[5] Free mem = 225431528
[6] Free mem = 225431528
[7] Free mem = 225431528
[8] Free mem = 225431528
[9] Free mem = 225431528
[10] Free mem = 225431528
[11] Free mem = 225431528
[12] Free mem = 225431528
[13] Free mem = 225431528
[14] Free mem = 225431528
[15] Free mem = 225431528
[16] Free mem = 225431528
[17] Free mem = 225431528
[18] Free mem = 225431528
[19] Free mem = 225431528
[20] Free mem = 225431528
[21] Free mem = 225431528
[22] Free mem = 225431528
[23] Free mem = 225431528
[24] Free mem = 225431528
[25] Free mem = 225431528
```

Runned with application startup:

```bash
krontab-loop-issue/app/build/distributions/app-shadow/bin$ ./app
OS: Linux-amd64-6.3.9-060309-generic
JVM: 17-BellSoft
Current system time: 2023-07-17T12:20:35.890791921Z
Running krontab...
[0] Free mem = 254478600
[1] Free mem = 250045616
[2] Free mem = 250045616
[3] Free mem = 250045616
[4] Free mem = 250045616
[5] Free mem = 250045616
[6] Free mem = 250045616
[7] Free mem = 250045616
[8] Free mem = 250045616
[9] Free mem = 250045616
[10] Free mem = 250045616
[11] Free mem = 250045616
```

**Comment by InsanusMokrassar** [comment] 2023-07-17 12:23
And run with `java -jar`:

```bash
krontab-loop-issue/app/build/libs$ java -jar app-all.jar 
OS: Linux-amd64-6.3.9-060309-generic
JVM: 17-BellSoft
Current system time: 2023-07-17T12:22:51.898114307Z
Running krontab...
[0] Free mem = 254023096
[1] Free mem = 249621720
[2] Free mem = 249621720
[3] Free mem = 249621720
[4] Free mem = 249621720
[5] Free mem = 249621720
[6] Free mem = 249621720
[7] Free mem = 249621720
[8] Free mem = 249621720
[9] Free mem = 249621720
[10] Free mem = 249621720
```

**Comment by InsanusMokrassar** [comment] 2023-07-19 10:31
> This problem is related to system time. So we need to set time to about 2023-06-28T16:00:00Z to reproduce it. :)

Could you please change the sample git repo to guarantee reproducing of bug? I am steel unable to catch it

**Comment by InsanusMokrassar** [comment] 2023-10-22 20:07
Closing according to inactivity and potentially exists fix

**Closed by InsanusMokrassar** 2023-10-22 20:07 UTC
Labels: bug, question, code
