### ISSUE TITLE
`next()` returns `null` on fixed date

### ISSUE THREAD

**Issue by DVDAndroid** [InsanusMokrassar/krontab#34] opened 2022-05-29 10:35 UTC
I'm using this library with `kotlinx-datetime`. I would like to schedule a task once at a specified time, but when I execute the code that task runs immediately

```kotlin
import dev.inmo.krontab.KronScheduler
import dev.inmo.krontab.builder.buildSchedule
import dev.inmo.krontab.doOnce
import dev.inmo.krontab.nextOrNow
import kotlinx.datetime.Clock
import kotlinx.datetime.LocalDateTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime
import kotlin.time.Duration.Companion.seconds

suspend fun main() {
  ((Clock.System.now().also {
    println("now:\t\t\t${it.toString().replace("T", "\t\t ")}")
  }) + 6.seconds).toLocalDateTime(TimeZone.UTC)
    .also { println("should run at:\t${it.toString().replace("T", "\t\t ")}") }
    .toCron()
    .also {
      println("next:\t\t\t${it.next()?.toStringDefault()}")
      println("nextOrNow:\t\t${it.nextOrNow().toStringDefault()}")
    }
    .doOnce {
      println("Hello at\t\t${it.toStringDefault()}")
    }
}


fun LocalDateTime.toCron(): KronScheduler = buildSchedule {
  seconds { at(second) }
  minutes { at(minute) }
  hours { at(hour) }
  dayOfMonth { at(dayOfMonth) }
  months { at(monthNumber) }
  years { at(year) }
}
```

output:
```
now:			2022-05-29	 10:33:18.742564200Z
should run at:		2022-05-29	 10:33:24.742564200
next:			null
nextOrNow:		Sun, 29 May 2022 10:33:19 UTC
Hello at		Sun, 29 May 2022 10:33:19 UTC
```

If I comment out `years { at(year) }` or `dayOfMonth { at(dayOfMonth) }` I think there's a infinite loop
If I comment out `months { at(monthNumber) }` code works fine at scheduled time

Where is the problem?

**Comment by InsanusMokrassar** [comment] 2022-06-03 04:41
Hello :) If I correctly understand, you are trying to setup fixed date with all possible fields. In that case will exist only one non nullable next result - that date. Besides, you will be able to get that result only when you will pass as a `now` in scheduler the date **before**. You are using `doOnce` which, as I remember, getting `DateTime.now()` and this one will always be greater that the one you have used to setup kron scheduler. As a result, you are getting null :)

**Comment by DVDAndroid** [comment] 2022-06-03 07:36
> you will be able to get that result only when you will pass as a `now` in scheduler the date **before**

I'm not sure to understand you mean for this sentence. How can I pass a `now` value?

> getting `DateTime.now()` and this one will always be greater that the one you have used to setup kron scheduler. As a result, you are getting null :)

`DateTime.now()` should be always lower than the date I setup in kron block (eg: `now` < `tomorrow`)

------

Could you provide a working example by editing code above or this is not feasible with this library?

**Comment by InsanusMokrassar** [comment] 2022-06-03 07:41
I got your point, will take a look closer a little bit later

**Comment by InsanusMokrassar** [comment] 2022-06-15 07:28
Will be fixed with release of 0.7.3. Sorry for the delay :(

**Closed by InsanusMokrassar** 2022-06-15 07:28 UTC

**Comment by DVDAndroid** [comment] 2022-06-15 08:08
Firstly, thanks

Tried build `0.7.3-branch_0.7.3-build118` and I had to minus 1 both day of month and month number
So now January = 0 and first day of month = 0?

**Comment by InsanusMokrassar** [comment] 2022-06-15 08:28
> Firstly, thanks
> 
> Tried build `0.7.3-branch_0.7.3-build118` and I had to minus 1 both day of month and month number So now January = 0 and first day of month = 0?

Yes :) by design it should be like this, but thank you for your report, I have fixed the issue
